/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/Button.vue')['default']
    GameGrid: typeof import('./../src/components/GameGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toggle: typeof import('./../src/components/Toggle.vue')['default']
    ToggleMode: typeof import('./../src/components/ToggleMode.vue')['default']
  }
}
